### PR TITLE
don't use babel-node in production

### PR DESCRIPTION
**Pull request by evq**

### CODE REVIEW

**Comment by mrose17** [comment]
just checking: this will still run on my mac without docker or any other "magic", right?

**Comment by mrose17** [comment]
hmmm... pilot error on my part?

    npm run build-ledger && npm run ledger-server
    
    > bat-ledger@0.9.0 build-ledger /Users/mrose/Documents/Projects/brave.com/bat-ledger
    > babel ledger -d dist/ledger
    
    ledger/controllers/address.js -> dist/ledger/controllers/address.js
    ledger/controllers/balance.js -> dist/ledger/controllers/balance.js
    ledger/controllers/provider.js -> dist/ledger/controllers/provider.js
    ledger/controllers/publisher.js -> dist/ledger/controllers/publisher.js
    ledger/controllers/registrar.js -> dist/ledger/controllers/registrar.js
    ledger/controllers/reports.js -> dist/ledger/controllers/reports.js
    ledger/controllers/surveyor.js -> dist/ledger/controllers/surveyor.js
    ledger/controllers/wallet.js -> dist/ledger/controllers/wallet.js
    ledger/server.js -> dist/ledger/server.js
    ledger/worker.js -> dist/ledger/worker.js
    ledger/workers/publisher.js -> dist/ledger/workers/publisher.js
    ledger/workers/rulesets.js -> dist/ledger/workers/rulesets.js
    ledger/workers/surveyor.js -> dist/ledger/workers/surveyor.js
    
    > bat-ledger@0.9.0 ledger-server /Users/mrose/Documents/Projects/brave.com/bat-ledger
    > NODE_PATH=dist node --optimize_for_size --max_old_space_size=460 --gc_interval=100 dist/ledger/server.js
    
    module.js:472
        throw err;
        ^
    
    Error: Cannot find module '../config.js'
        at Function.Module._resolveFilename (module.js:470:15)
        at Function.Module._load (module.js:418:25)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/Users/mrose/Documents/Projects/brave.com/bat-ledger/dist/ledger/server.js:8:16)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)

**Comment by evq** [comment]
@mrose17 try the full `npm run build`, `config.js` is copied during that

**Comment by evq** [comment]
also, `start-ledger` etc still work for dev use case where it's okay to use babel-node

**Comment by mrose17** [comment]
right! LGTM. please merge.

**Pull request merged**
