### PR TITLE
add helper function for setting mongo schema for collection

### PR DESCRIPTION
**Pull request by evq**
also adds a schema for the `restricted` collection as an example

### CODE REVIEW

**Comment by evq** [comment]
this enforces schemas even during manual edits. using `Joi` can't give us that. I agree the syntax leaves much to be desired - the jsonSchema support that was added later is better but unfortunately not supported for our mongo version.

**Comment by mrose17** [comment]
we can either upgrade to mongo 3.6 or use joi in the interim. the syntax in 3.4 is a "dead letter".

**Comment by evq** [comment]
I'm all for switching to 3.6 but I don't agree that using Joi in the interim makes more sense than using this syntax until then

**Comment by mrose17** [comment]
we use joi throughout all the code, and in may repos. it is well-understood. the pre 3.6-syntax would e a one-off.

**Comment by evq** [comment]
the pre 3.6-syntax is standard mongo query syntax which we also make use of :)

**Comment by mrose17** [comment]
ok, let's use the mongo syntax. however, can we structure the .code so that the schema is an optional property for each object in the array passed to checkIndices, so that checkIndices can do the test if the property is present on any of them?

**Comment by evq** [comment]
OBE

**Pull request closed without merging**
