### PR TITLE
add graceful error handling for use of legacy surveyor

### PR DESCRIPTION
**Pull request by evq**

### CODE REVIEW

**Comment by mrose17** [comment]
do we have any test output or other means of verification? would it be better to simply add cohorts to the ("few") legacy surveyors in use...

**Comment by evq** [comment]
```
[user@work:~/source/bat-ledger]% docker-compose run --rm -v $(pwd)/test:/usr/src/app/test ledger-web npm run test-integration -- -m "integration : v2 grant contribution workflow with uphold BAT wallet"
Starting ledger-redis ... done
Starting ledger-mongo ... done

> bat-ledger@0.9.0 test-integration /usr/src/app
> ava test/*.integration.test.js "-m" "integration : v2 grant contribution workflow with uphold BAT wallet"


 ⠴   ava ipc stats:
Wed, 10 Jan 2018 01:04:00 GMT superagent GET https://ledger-staging.mercury.basicattentiontoken.org/v2/registrar/persona
Wed, 10 Jan 2018 01:04:01 GMT superagent GET https://ledger-staging.mercury.basicattentiontoken.org/v2/registrar/persona -> 200
created new ed25519 keypair
{"publicKey":"3d95d30a2aa43e7bda4366c9cdc0e0670b74ac03797eebe729b9617bbbab8c05","secretKey":"1c9e9a1afe230802f6f9960b7b31503a7aece1bcdfd1c62df8f6e39dd09919473d95d30a2aa43e7bda4366c9cdc0e0670b74ac03797eebe729b9617bbbab8c05"}
Wed, 10 Jan 2018 01:04:01 GMT superagent POST https://ledger-staging.mercury.basicattentiontoken.org/v2/registrar/persona/277fc697402ad389f306f81b7f15784
Wed, 10 Jan 2018 01:04:05 GMT superagent POST https://ledger-staging.mercury.basicattentiontoken.org/v2/registrar/persona/277fc697402ad389f306f81b7f15784 -> 200
Signature verified in registerUserFinal.
Wed, 10 Jan 2018 01:04:05 GMT superagent GET https://ledger-staging.mercury.basicattentiontoken.org/v2/surveyor/contribution/current/277fc697402ad389f306f81b7f15784
Wed, 10 Jan 2018 01:04:05 GMT superagent GET https://ledger-staging.mercury.basicattentiontoken.org/v2/surveyor/contribution/current/277fc697402ad389f306f81b7f15784 -> 200
Wed, 10 Jan 2018 01:04:05 GMT superagent GET https://ledger-staging.mercury.basicattentiontoken.org/v1/grants
Wed, 10 Jan 2018 01:04:05 GMT superagent GET https://ledger-staging.mercury.basicattentiontoken.org/v1/grants -> 200
Wed, 10 Jan 2018 01:04:05 GMT superagent PUT https://ledger-staging.mercury.basicattentiontoken.org/v1/grants/34648580-c903-4ed5-abfe-95ce4830256c
Wed, 10 Jan 2018 01:04:06 GMT superagent PUT https://ledger-staging.mercury.basicattentiontoken.org/v1/grants/34648580-c903-4ed5-abfe-95ce4830256c -> 200
{ altcurrency: 'BAT', probi: '30000000000000000000' }
Wed, 10 Jan 2018 01:04:06 GMT superagent GET https://ledger-staging.mercury.basicattentiontoken.org/v2/wallet/34648580-c903-4ed5-abfe-95ce4830256c?refresh=true&amount=30&altcurrency=BAT
Wed, 10 Jan 2018 01:04:07 GMT superagent GET https://ledger-staging.mercury.basicattentiontoken.org/v2/wallet/34648580-c903-4ed5-abfe-95ce4830256c?refresh=true&amount=30&altcurrency=BAT -> 200
Wed, 10 Jan 2018 01:04:08 GMT superagent PUT https://ledger-staging.mercury.basicattentiontoken.org/v2/wallet/34648580-c903-4ed5-abfe-95ce4830256c
Wed, 10 Jan 2018 01:04:38 GMT superagent PUT https://ledger-staging.mercury.basicattentiontoken.org/v2/wallet/34648580-c903-4ed5-abfe-95ce4830256c -> 503

...

  Rejected promise returned by test. Reason:

  Error {
    message: `{␊
      "statusCode": 422,␊
      "error": "Unprocessable Entity",␊
      "message": "cannot perform a contribution using a legacy surveyor"␊
    }`,
  }
```

**Comment by mrose17** [comment]
1. good catch on https://github.com/brave-intl/bat-ledger/pull/109/commits/d275cab45ad16127c237a3ec27a49ae597809c25

2. with respect to

    would it be better to simply add cohorts to the ("few") legacy surveyors in use...

my guess is that the answer is "no". would you confirm? thanks!

**Comment by evq** [comment]
yeah I would prefer to avoid that

**Comment by mrose17** [comment]
thanks. just checking.

**Pull request merged**
